### ISSUE TITLE
Vulnerable for SQL injection

### ISSUE THREAD

**Issue by marcojanssen** [miguelavaqrod/bolt-newsletter-subscription#2]
There is no escaping applied at every query making it vulnerable to SQL injection. Could also use prepared statements. 

https://github.com/miguelavaqrod/bolt-newsletter-subscription/blob/master/Extension.php#L42

**Comment by miguelavaqrod** [comment]
Hi!

I do apologize, but I was unable to stay in contact.
Going to check it...

**Comment by nbehier** [comment]
That seems solve with the last PR #4 . 
@miguelavaqrod Could you create a release for Bolt v3 ?

**Comment by miguelavaqrod** [comment]
OMG...
@nbehier I do apologize for this big delay in answering you.
I checked that you forked the repo and fixed those issues.
I will merge your fixes in this repo so people can update their code if needed.
Thanks a lot.
