### ISSUE TITLE
Could not install this extension

### ISSUE THREAD

**Issue by JarJak** [miguelavaqrod/bolt-newsletter-subscription#6]
Error I get is:

`Extension package miguelavaqrod/newsletter has an invalid class 'Bolt\Extension\Miguelavaqrod\Newsletter\NewsletterExtension' and has been skipped.`

**Comment by miguelavaqrod** [comment]
Hi Jar:

Seeing that Bolt has evolved a lot, maybe this extension will not work anymore so I would need to update it.
Right now I am not using Bolt, and have no time to develop a new update, but I know there are some forks and maybe there they can help you, at least, quicker than me.

Sorry.

**Comment by miguelavaqrod** [comment]
I can not check it by my own, but people is still using the extension.
I have applied some PRs sent , so I think it can work.
